# Generated by Django 5.1.4 on 2024-12-19 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpyCat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spycat",
            name="salary",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
